# Generated by Django 4.2.4 on 2023-08-31 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_room_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
