# Generated by Django 4.2.4 on 2023-08-31 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='update',
            new_name='updated',
        ),
    ]
